apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
 name: ops-manager
 namespace: mongodb
spec:
 replicas: 1
 version: "5.0.0"
 adminCredentials: ops-manager-admin-secret
 externalConnectivity:
  type: NodePort
 applicationDatabase:
  members: 3
  version: "5.0.5-ent"
