apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-project-cluster
  namespace: mongodb
spec:
  members: 3
  version: "5.0.5-ent"
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: my-project
  credentials: organization-secret
